Repository AY2122S1-CS2103T-W08-3/tp, pull requests merged in 2021-11, with the labels that each got.

#223 Improve body measurement field
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Measurement.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/ModelStub.java
Labels: type.Bug, severity.High

#135 Updated the diagrams for Model and Storage component
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#251 Fixed the order ID replication problem
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/storage/JsonSerializableOrderBook.java
Labels: priority.High

#243 Add test cases to logic classes - Chi Sern
  src/main/java/seedu/address/logic/parser/FindOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/OrderUtil.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#244 Add test cases to logic classes (Part 2) - Chi Sern
  src/main/java/seedu/address/logic/parser/SortOrdersCommandParser.java
  src/test/data/JsonSerializableTaskBookTest/typicalTasksTaskBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortOrdersCommandParserTest.java
Labels: type.Task, priority.High

#269 Duplicate orders check
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/model/Date.java
  src/main/java/seedu/address/model/order/OrderList.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
Labels: type.Bug, severity.High

#288 Fix duplicate orders bug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonSerializableOrderBook.java
Labels: documentation

#281 Fix duplicate order bug
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/data/JsonSerializableTaskBookTest/duplicateTaskTaskBook.json
  src/test/java/seedu/address/model/TaskBookTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
Labels: type.Bug, severity.High

#291 Update DG - Tanishq
  docs/DeveloperGuide.md
  docs/diagrams/SortOrderCommandSequenceDiagram.puml
  docs/diagrams/SortOrdersCommandClassDiagram.puml
  docs/diagrams/SortOrdersModelSequenceDiagram.puml
  docs/diagrams/SortOrdersParserSequenceDiagram.puml
  docs/images/SortOrdersCommandClassDiagram.png
  docs/images/SortOrdersCommandSequenceDiagram.png
  docs/images/SortOrdersModelSequenceDiagram.png
  docs/images/SortOrdersParserSequenceDiagram.png
Labels: documentation

#294 Tasks with 'General' tag are not handled properly
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, severity.High

#286 DG Appendix: Manual Testing
  docs/DeveloperGuide.md
  docs/images/TotalOrdersSequenceDiagram0.png
Labels: documentation
