Repository AY2122S1-CS2103T-W08-3/tp, pull requests merged in 2021-10, with the labels that each got.

#29 update index.md
  docs/index.md
Labels: type.Task, priority.Low

#40 Update aboutus
  docs/AboutUs.md
Labels: severity.VeryLow

#53 Improve GUI and fix markcommand bug
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/sales_note.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TaskCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/main/resources/view/Toggle.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.Medium

#57 Update version number for jar release
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: hacktoberfest-accepted

#91 Display Orders
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/OrderCard.fxml
Labels: type.Task, priority.High

#146 Fix 'undefined state' bug
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, severity.High
